version: "3.9"

services:
  telegraf:
    image: telegraf:1.29.2
    # https://hub.docker.com/_/telegraf
    container_name: telegraf
    restart: unless-stopped
    # 8125/udp for Statsd used for Gunicorn metrics
    ports:
      - "127.0.0.1:8125:8125/udp"
    hostname: ${HOSTNAME:-web-aura-sinp}
    # To authorize telgraf to access to /run/docker.sock set host docker gid
    # Find docker gid with: stat -c '%g' /var/run/docker.sock
    user: "telegraf:${DOCKER_GID:-998}"
    group_add:
      - adm
    environment:
      HOSTNAME: ${HOSTNAME:-web-aura-sinp}
      HOST_MOUNT_PREFIX: /host
      HOST_ETC: /host/etc
      HOST_PROC: /host/proc
      HOST_PROC_MOUNTINFO: /proc/1
      HOST_RUN: /host/run
      HOST_SYS: /host/sys
      HOST_VAR: /host/var
      INFLUXDB2_INIT_ORG: ${INFLUXDB2_INIT_ORG}
      INFLUXDB2_INIT_BUCKET: ${INFLUXDB2_INIT_BUCKET}
      INFLUXDB2_TELEGRAF_TOKEN: ${INFLUXDB2_TELEGRAF_TOKEN}
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /:/host:ro
      - /run/docker.sock:/run/docker.sock:ro
      - /run/utmp:/host/var/run/utmp
      - /opt/srvstatus/status.json:/opt/srvstatus/status.json
      #- ./certs/ca.pem:/etc/docker/ssl/ca.pem:ro
      #- ./certs/client-cert.pem:/etc/docker/ssl/client-cert.pem:ro
      #- ./certs/client-key.pem:/etc/docker/ssl/client-key.pem:ro

networks:
  default:
    name: nginx-proxy
    external: true
