version: "3.9"

services:
  manager-portainer:
    # https://hub.docker.com/r/portainer/portainer-ce
    image: portainer/portainer-ce:2.16.1
    container_name: "manager-portainer"
    restart: unless-stopped
    expose:
      - 8000
    ports:
      - "127.0.0.1:9000:9000"
    hostname: ${HOSTNAME:-sinp-paca-web}
    command: --admin-password ${ENCRYPTED_PASSWORD}
    command: -H unix:///var/run/docker.sock
    volumes:
      # Try to change timezone for "Display timestamps" in log view => but don't work !
      # See: https://github.com/portainer/portainer/issues/913
      - /usr/share/zoneinfo/Europe/Paris:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-storage:/data

volumes:
  portainer-storage:

networks:
  default:
    external:
      name: ${NETWORK:-nginx-proxy}
