version: "3.9"

services:
  borgmatic:
    build:
      context: ./build
      dockerfile: Dockerfile
      args:
        - MAILTO=${MAILTO}
        - PGSQL_MAJOR_VERSION=${PGSQL_MAJOR_VERSION}
    image: cbn-alpin/borgmatic:2023.12.18
    # https://hub.docker.com/r/b3vis/borgmatic/
    container_name: borgmatic
    restart: unless-stopped
    hostname: ${HOSTNAME:-sinp-aura-web}
    env_file:
      - .env
      - msmtp.env
    environment:
      TZ: ${TZ:-Europe/Paris}
    volumes:
      - ${VOLUME_SOURCE}:/mnt/source:ro                         # backup source
      - ${VOLUME_TARGET}:/mnt/borg-repository                   # backup target
      - ${VOLUME_BORG_CONFIG}:/root/.config/borg                # config and keyfiles
      - ${VOLUME_SSH}:/root/.ssh                                # ssh key for remote repositories
      - ${VOLUME_BORG_CACHE}:/root/.cache/borg                  # checksums used for deduplication
      - ./config/aliases.txt:/etc/aliases:ro                    # Email aliases for container users (used by Msmtp)
      - ./config/borgmatic.yml:/etc/borgmatic.d/config.yaml     # borgmatic config file
      - ./config/ntfy.yml:/root/.config/ntfy/ntfy.yml:ro        # Ntfy config file

networks:
  default:
    name: nginx-proxy
    external: true
