version: "3.9"

services:
  borgmatic:
    build:
      context: ./build
      dockerfile: Dockerfile
      args:
        - MAILTO=${MAILTO}
    image: cbn-alpin/borgmatic:1.0.0
    # https://hub.docker.com/r/b3vis/borgmatic/
    container_name: borgmatic
    restart: unless-stopped
    hostname: ${HOSTNAME:-sinp-aura-db}
    env_file:
      - .env
      - msmtp.env
    networks:
      - nginx-proxy
    volumes:
      - ${VOLUME_SOURCE}:/mnt/source:ro                         # backup source
      - ${VOLUME_TARGET}:/mnt/borg-repository                   # backup target
      - ${VOLUME_BORG_CONFIG}:/root/.config/borg                # config and keyfiles
      - ${VOLUME_SSH}:/root/.ssh:ro                             # ssh key for remote repositories
      - ${VOLUME_BORG_CACHE}:/root/.cache/borg                  # checksums used for deduplication
      - ./config/aliases.txt:/etc/aliases:ro                    # Email aliases for container users (used by Msmtp)
      - ./config/borgmatic.yml:/etc/borgmatic.d/config.yaml     # borgmatic config file
      - ./config/ntfy.yml:/root/.config/ntfy/ntfy.yml:ro        # Ntfy config file

networks:
  nginx-proxy:
    external: true