###############################################################################
# NOTES : après toute modification dans ce fichier, il est nécessaire de
#         mettre à jour GeoNature à l'aide de la commande :
#         'geonature update_configuration'
###############################################################################

DEBUG = false

#############################################
# GeoNature backend global configuration file
#############################################

# Database
SQLALCHEMY_DATABASE_URI = "postgresql://<user>:<password>@10.0.1.20:5432/geonature2db"
URL_APPLICATION = "https://donnees.biodiversite-auvergne-rhone-alpes.fr"
API_ENDPOINT = "https://donnees.biodiversite-auvergne-rhone-alpes.fr/api"
API_TAXHUB = "https://taxons.biodiversite-aura.fr/api"

# Remplacer par une clé alétoire complexe
SECRET_KEY = "<secret-key>"

# Langue principale par défaut
DEFAULT_LANGUAGE = "fr"

# Enable logging email error (must fill the mail config section bellow if true)
MAIL_ON_ERROR = false

# Nom de l'application dans la page d'accueil.
appName = "Biodiv'AURA Expert"

# Set Sentry DSN
SENTRY_DSN = "https://<uuid-dsn>@app-monitor.biodiversite-aura.net/1"

[ALEMBIC]
VERSION_LOCATIONS = "/home/geonat/www/usershub/app/migrations/versions/"

#######################################################################################
###### Si vous souhaitez surcoucher certains paramètres,
###### compléter les sections ci-dessous à partir du modèle default_config.toml.example
#######################################################################################

# Configuration de l'envoie d'emails
# TODO: revoir la config pour utiliser le serveur Postfix local
[MAIL_CONFIG]
    MAIL_SERVER = "ssl0.ovh.net"
    MAIL_PORT = 587
    MAIL_USE_TLS = true
    MAIL_USE_SSL = false
    MAIL_USERNAME = "<email-username>"
    MAIL_PASSWORD = "<email-password>"
    MAIL_DEFAULT_SENDER = "Ne Pas Réponde <email-default-sender>"
    MAIL_ASCII_ATTACHMENTS = false
    # email(s) to the administrator for the email logging
    ERROR_MAIL_TO = ["<email-error>"]

# Configuration de l'accès distant à UsersHub (API)
[USERSHUB]
    URL_USERSHUB = "https://gestion.biodiversite-aura.fr" # sans slash final
    # Administrateur de mon application
    ADMIN_APPLICATION_LOGIN = "<user-admin-login>"
    ADMIN_APPLICATION_PASSWORD = "<user-admin-password>"

# Configuration de l'accès sans authentification
[PUBLIC_ACCESS]
    ENABLE_PUBLIC_ACCESS = true
    PUBLIC_LOGIN = "user-public"
    PUBLIC_PASSWORD = "<public-password>"

# Gestion des demandes d'inscription
[ACCOUNT_MANAGEMENT]
    ENABLE_SIGN_UP = true
    AUTO_ACCOUNT_CREATION = false
    VALIDATOR_EMAIL = [
            "Ornella KRISTO <o.kristo@cbn-alpin.fr>",
            "Lucile VAHE <l.vahe@cbn-alpin.fr>",
            "Mélanie PIROUX <melanie.piroux@cbnmc.fr>",
            "Donovan MAILLARD <donovan.maillard@flavia-ape.fr>",
            "Julien GIRARD-CLAUDON <julien.girard-claudon@lpo.fr>",
            "M. CHAUTAN <m.chautan@chasseauvergnerhonealpes.com>",
            "webmaster@biodiversite-aura.fr",
        ]
    AUTO_DATASET_CREATION = false
    ENABLE_USER_MANAGEMENT = true
    ADDON_USER_EMAIL = """<p>
	    Nous vous rappelons que les données de Biodiv'AURA sont diffusées en accès
            libre avec leur précision géographique maximale, hors données sensibles,
            via le bouton "accès public". La création de compte est nécessaire uniquement
            pour demander un
            <a href="https://www.biodiversite-auvergne-rhone-alpes.fr/wp-content/uploads/2024/05/acces_aux_donnees_sensibles_SINP_AURA-_VF2024.pdf">
                accès à la localisation précise des données sensibles
            </a> ».<br/>
            L'accès aux données sensibles précises nécessite de compléter un «
            <a href="https://donnees.biodiversite-auvergne-rhone-alpes.fr/\u0023/permissions/requests/add">
                formulaire de demande d'accès aux données sensibles précises
            </a> ».<br/>
            L'accord sera formalisé par l'acceptation d'une convention
            « droit d'accès aux données sensibles précises »
            et donnera lieu à l'attribution d'un accès direct à ces données.
            </p>"""
    # Gestion du formulaire de demande d'inscription
    [[ACCOUNT_MANAGEMENT.ACCOUNT_FORM]]
        type_widget = "html"
        attribut_name = "conditions"
        class = "alert alert-primary"
        html = """
            <p>
                Les données de Biodiv'AURA sont diffusées en accès libre avec leur précision
                géographique maximale, hors données sensibles, via le bouton "accès public".
                La création de compte est nécessaire uniquement pour demander
                <a href="https://www.biodiversite-auvergne-rhone-alpes.fr/wp-content/uploads/2024/05/acces_aux_donnees_sensibles_SINP_AURA-_VF2024.pdf" target="_blank">
                    un accès à la localisation précise des données sensibles
                </a>.
            </p>
            <p>
                Les données et informations qui vous sont fournies dans le cadre de Biodiv'AURA
                Expert ne sont pas exhaustives et peuvent donc s'avérer insuffisantes pour les
                besoins spécifiques de votre étude. Une réactualisation de ces données dans le
                cadre d'inventaires complémentaires est nécessaire.
            </p>"""
        required = false

# Configuration générale du frontend
[FRONTEND]
    # Affiche la carte des 100 obs sur la page d'accueil
    DISPLAY_MAP_LAST_OBS = false

    # Durée de vie du cache des stats de la page d'accueil
    # 864 000 = 10 jours
    STAT_BLOC_TTL = 864000

    # Affiche le composant 'custom/components/footer' sur la page d'accueil
    DISPLAY_FOOTER = true

    # Activer l'affichage des informations liées aux profils de taxons
    ENABLE_PROFILES = true

# Configuration cartographique
[MAPCONFIG]
    # Attention : les coordonnées sont au format [Y, X]
    # Cf leaflet configuration (https://leafletjs.com/reference-1.4.0.html#latlng-l-latlng)
    CENTER = [45.29619, 4.66072]
    # Zoom par défaut
    ZOOM_LEVEL = 8
    # Zoom à partir duquel on peut pointer un relevé
    ZOOM_LEVEL_RELEVE = 15
    # Zoom appliqué sur la carte lorsque l'on clique sur une liste
    ZOOM_ON_CLICK = 16
    # Configuration des fonds carto
    BASEMAP = [
        {"name" = "OpenStreetMap",    "layer" = "//tile.openstreetmap.org/{z}/{x}/{y}.png", "attribution" = 'Fond de carte & données par <a href="https://www.openstreetmap.org/copyright" target="_blank">&copy; les contributeurs & contributrices OpenStreetMap</a>, sous <a href="https://opendatacommons.org/licenses/odbl/1.0/" target="_blank">licence ODbL</a>.', "maxZoom" = 22, "maxNativeZoom" = 19},
        {"name" = "OpenTopoMap", "layer" = "//{s}.tile.opentopomap.org/{z}/{x}/{y}.png", "attribution" = 'Fond de carte par <a href="https://opentopomap.org" target="_blank">OpenTopoMap</a>, sous <a href="https://creativecommons.org/licenses/by-sa/2.0/fr/" target="_blank">licence CC BY-SA</a>. Données <a href="https://www.openstreetmap.org/copyright" target="_blank">&copy; les contributeurs & contributrices OpenStreetMap</a>, sous <a href="https://opendatacommons.org/licenses/odbl/1.0/" target="_blank">licence ODbL</a> ; <a href="http://viewfinderpanoramas.org">SRTM</a>.', "maxZoom" = 22, "maxNativeZoom" = 17},
        {"name" = "GoogleSatellite",  "layer" = "//{s}.google.com/vt/lyrs=s&x={x}&y={y}&z={z}", "subdomains" = ["mt0", "mt1", "mt2", "mt3"], "attribution" = "&copy; GoogleMap", "maxZoom" = 22, "maxNativeZoom" = 22},
        {"name" = "IGN Ortho",        "layer" = "https://data.geopf.fr/wmts?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&STYLE=normal&TILEMATRIXSET=PM&TILEMATRIX={z}&TILEROW={y}&TILECOL={x}&LAYER=HR.ORTHOIMAGERY.ORTHOPHOTOS&FORMAT=image/jpeg", "attribution" = "&copy; IGN", "maxZoom" = 22, "maxNativeZoom" = 19},
        {"name" = "IGN Cadastre",     "layer" = "https://data.geopf.fr/wmts?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&STYLE=normal&TILEMATRIXSET=PM&TILEMATRIX={z}&TILEROW={y}&TILECOL={x}&LAYER=CADASTRALPARCELS.PARCELS&FORMAT=image/png", "attribution" = "&copy; IGN", "maxZoom" = 22, "maxNativeZoom" = 19},
        {"name" = "IGN Plan v2",      "layer" = "https://data.geopf.fr/wmts?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&STYLE=normal&TILEMATRIXSET=PM&TILEMATRIX={z}&TILEROW={y}&TILECOL={x}&LAYER=GEOGRAPHICALGRIDSYSTEMS.PLANIGNV2&FORMAT=image/png", "attribution" = "&copy; IGN", "maxZoom" = 22, "maxNativeZoom" = 19},
        {"name" = "BRGM Géologie", "url" = "https://geoservices.brgm.fr/WMS-C/?", "service" = "wms", "layers" = "GEOLOGIE", "attribution" = '&copy; BRGM - <a href="https://infoterre.brgm.fr/viewer/" target="_blank">BD Charm-50</a>'}
    ]

# CRITICAL: 50 ; ERROR: 40 ; WARNING: 30 ; INFO: 20 ; DEBUG: 10 ; NOTSET: 0
[SERVER]
    LOG_LEVEL = 20

# Configuration de la Synthese
[SYNTHESE]
    # Liste des entités géographiques sur lesquelles les filtres géographiques de la synthese s'appuient
    # (id_area = id de l'entité géo, table ref_geo.bib_areas_types).
    AREA_FILTERS = [
        { label = "Communes", type_code = "COM" },
        { label = "Départements", type_code = "DEP" },
    ]
    # Nombre d'observation maximum à afficher sur la carte après une recherche
    NB_MAX_OBS_MAP = 100000
    # Nombre des dernières observations affichées par défaut quand on arrive sur la synthese
    NB_LAST_OBS = 0
    # Colonne à afficher par défaut sur la liste des résultats de la synthese
    # Choisir le champ 'prop' parmis les colonnes suivante
    # (id_synthese, date_min, cd_nom, lb_nom, nom_vern_or_lb_nom, st_asgeojson, observers, dataset_name, url_source)
    LIST_COLUMNS_FRONTEND = [
        { prop = "lb_nom", name = "Taxon" },
        { prop = "date_min", name = "Date début" },
        { prop = "observers", name = "Observateurs" },
        { prop = "dataset_name", name = "Jeu de données" }
    ]
    # Affiche (=true) ou masque (=false) l'arbre de recherche taxonomique
    # dans la recherche taxonomique avancée.
    DISPLAY_TAXON_TREE = false

    # Nombre max d'observation dans les exports
    # WARNING : Au 2020-11-12, un bug empêche d'avoir une valeur différente pour les export.
    NB_MAX_OBS_EXPORT = 100000

    # Noms des colonnes obligatoires de la vue ``gn_synthese.v_synthese_for_export``
    EXPORT_ID_SYNTHESE_COL = "id_synthese"
    EXPORT_ID_DATASET_COL = "jdd_id"
    EXPORT_ID_DIGITISER_COL = "id_digitiser"
    EXPORT_OBSERVERS_COL = "observateurs"
    EXPORT_GEOJSON_4326_COL = "geojson_4326"
    EXPORT_GEOJSON_LOCAL_COL = "geojson_local"

    # Noms des colonnes obligatoires de la vue ``gn_synthese.v_metadata_for_export``
    EXPORT_METADATA_ID_DATASET_COL = "jdd_id"

    # Champs à afficher dans l'export
    # Voir les noms des champs de la ``vue gn_synthese.v_synthese_for_export``
    EXPORT_COLUMNS = [
        "uuid_perm_sinp",
        "uuid_perm_grp_sinp",
        "jdd_nom",
        "jdd_uuid",
        "fournisseur",
        "observateurs",
        "determinateurs",
        "cd_ref",
        "nom_valide",
        "nom_vernaculaire",
        "classe",
        "famille",
        "ordre",
        "statut_observation",
        "nombre_min",
        "nombre_max",
        "date_debut",
        "date_fin",
        "geojson_4326",
        "x_centroid_4326",
        "y_centroid_4326",
        "precision_geographique",
        "communes",
        "alti_min",
        "technique_observation",
        "stade_vie",
        "statut_biologique",
        "sexe",
        "comportement",
        "type_source",
        "type_precision",
        "sensibilite",
        "confidentialite",
        "floutage",
        "statut_validation",
        "statut_pn",
        "statut_pr",
        "statut_pd",
        "statut_lrn",
        "statut_lrr",
        "statut_lrd",
        "statut_zdet",
        "statut_dh",
        "statut_do",
    ]
    ENABLE_AREA_AGGREGATION = true
    AREA_AGGREGATION_TYPE = "M5"
    AREA_AGGREGATION_BY_DEFAULT = false
    # Liste de 'id_attribut' TaxHub à afficher dans :
    # - la modale du détail d'une observation
    # - les filtres taxonomique avancés
    ID_ATTRIBUT_TAXHUB = [109]

[SYNTHESE.DEFAULT_FILTERS]
    # Statuts de validation : Certain, Probable
    # Il faut bien les renseigner en tant que chaîne de caractère (et non en tant que nombre)
    cd_nomenclature_valid_status = ['0', '1', '2']
    # Seulement les données de présence
    cd_nomenclature_observation_status = ['Pr']

[PERMISSION_MANAGEMENT]
    # Activer (=true) l'affichage du lien vers le formulaire de demande
    # de permissions. Par défaut : désactivé (=false).
    ENABLE_ACCESS_REQUEST = true
    # Activer la possibilité de demander l'accès aux données sensibles.
    ENABLE_SENSITIVE_ACCESS = true
    # Rend obligatoire la coche de l'accès aux données sensibles.
    ENABLE_MANDATORY_SENSITIVE_ACCESS = true
    # Types zones géo formulaire de demande d'accès.
    AREA_TYPES = ["COM", "DEP", "SINP"]
    # Durée minimum en jour pendant laquelle l'accès est autorisé.
    DEFAULT_ACCESS_DURATION = 30
    # Durée maximum en jour pendant laquelle l'accès peut être autorisé.
    MAX_ACCESS_DURATION = 1095
    # Email du validateur des permissions d'accès.
    VALIDATOR_EMAIL = [
            "Ornella KRISTO <o.kristo@cbn-alpin.fr>",
            "Lucile VAHE <l.vahe@cbn-alpin.fr>",
            "Mélanie PIROUX <melanie.piroux@cbnmc.fr>",
            "Donovan MAILLARD <donovan.maillard@flavia-ape.fr>",
            "Julien GIRARD-CLAUDON <julien.girard-claudon@lpo.fr>",
            "M. CHAUTAN <m.chautan@chasseauvergnerhonealpes.com>",
            "webmaster@biodiversite-aura.fr",
        ]

    # Activer la validation de la convention suite à une demande d'accès
    ENABLE_CONVENTION = true
    # Titre de la fenêtre modale affichant la convention
    CONVENTION_TITLE = "Convention « Droit d'accès ponctuel aux données sensibles précises de Biodiv’AURA Expert »"
    # Libellé du bouton permettant d'accepter la convention
    CONVENTION_VALIDATE = "J'accepte les termes de la convention « droit d'accès »."

    # Titre de la section personnalisable du formulaire de demande d'accès
    REQUEST_FORM_TITLE = "Motivations de la demande"
    # Définition de la section personnalisable du formulaire de demande
    # de permission d'accès.
    [[PERMISSION_MANAGEMENT.REQUEST_FORM]]
        type_widget = "html"
        attribut_name = "motivationIntro"
        html = """
            <small class="form-text text-muted">
                Veuillez décrire ci-dessous les motivations à l'origine
                de votre demande.
            </small>"""
    [[PERMISSION_MANAGEMENT.REQUEST_FORM]]
        type_widget = "select"
        attribut_label = "Règne concerné"
        attribut_name = "kingdom"
        icon = "fa-sitemap"
        icon_set = "fa"
        values = [
                "Végétal",
                "Animal (Invertébrés)",
                "Végétal et Animal (Invertébrés)",
            ]
        required = true
        help = """Veuillez indiquer le règne des taxons
            concernés par votre étude et pour lesquels vous demandez
            un accès précis."""
    [[PERMISSION_MANAGEMENT.REQUEST_FORM]]
        type_widget = "text"
        attribut_label = "Organisme"
        attribut_name = "userOrganism"
        icon = "business"
        required = true
        help = """Veuillez indiquer le nom de l'organisme auquel vous
            appartenez."""
    [[PERMISSION_MANAGEMENT.REQUEST_FORM]]
        type_widget = "select"
        attribut_label = "Type d'étude ou de projet"
        attribut_name = "projectType"
        icon = "fa-tag"
        icon_set = "fa"
        values = [
            "Plan de gestion",
            "DOCOB Natura 2000",
            "Inventaire scientifique",
            "Expertise écologique réglementaire",
            "Étude trame verte et bleue",
            "PLU / SCOT",
            "Autre (à préciser dans description)"]
        required = true
    [[PERMISSION_MANAGEMENT.REQUEST_FORM]]
        type_widget = "textarea"
        attribut_label = "Commanditaire"
        attribut_name = "projectSponsor"
        icon = "request_quote"
        required = true
        rows = 4
        help = """Veuillez indiquer le nom du commanditaire de l'étude ou
            l'organisme à l'origine du projet."""
    [[PERMISSION_MANAGEMENT.REQUEST_FORM]]
        type_widget = "textarea"
        attribut_label = "Description"
        attribut_name = "projectDescription"
        icon = "text_snippet"
        required = false
        rows = 10
        help = """Précisez le calendrier, la finalité, l'objet de l'étude
            scientifique et le cadre réglementaire dans lequel s'inscrit
            la demande (Étude d'impact, étude d'incidence Natura 2000,
            étude d'incidence Eau, demande d'autorisation au titre de la
            loi sur l'eau, demande d'autorisation au titre des ICPE,
            demande d'autorisation de destruction d'espèces protégées)."""

[DATA_BLURRING]
    # Activer (=true) l'affichage du floutage des données.
    ENABLE_DATA_BLURRING = true
    # Correspondance entre les niveau de diffusion (nomenclaure NIV_PRECIS)
    # et un type de zone géographique utilisée pour le rendu sur les cartes.
    AREA_TYPE_FOR_DIFFUSION_LEVELS = [
            #{level = "0", area = "M5"},# Standard => pas de floutage ! 2025-03-19 -- jpmilcent
            {level = "1", area = "M5"},# Commune
            {level = "2", area = "M5"},# Maille
            {level = "3", area = "M5"},# Département
        ]
    # Correspondance entre les niveau de sensibilité (nomenclaure SENSIBILITE)
    # et un type de zone géographique utilisée pour le rendu sur les cartes.
    AREA_TYPE_FOR_SENSITIVITY_LEVELS = [
            {level = "1", area = "M5"},# Commune
            {level = "2", area = "M5"},# Maille
            {level = "3", area = "M5"},# Département
            {level = "2.1", area = "M1"},
            {level = "2.2", area = "M2"},
            {level = "2.3", area = "M5"},
            {level = "2.4", area = "M10"},
            {level = "2.5", area = "M20"},
            {level = "2.6", area = "M50"},
            {level = "2.7", area = "M50"},
        ]
    # Nom de la colonne du fichier d'export de la Synthese contenant les informations
    # de la nomenclature DEE_FLOU. La présence de cette colonne n'est pas obligatoire.
    # Si présente, sa valeur est forcée a OUI si la donnée a été floutée par le niveau de
    # sensibilité.
    EXPORT_FIELD_BLURRING = "floutage"

